# Generated by Django 5.2.6 on 2025-10-21 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('reserva', 'Reserva'), ('reseña', 'Reseña'), ('sistema', 'Sistema'), ('mensaje', 'Mensaje')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='type',
            field=models.CharField(choices=[('reserva', 'Reserva'), ('reseña', 'Reseña'), ('sistema', 'Sistema'), ('mensaje', 'Mensaje')], max_length=20, unique=True),
        ),
    ]
