# Generated by Django 5.2.6 on 2026-01-31 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_push_tokens_and_reminders'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pushdevicetoken',
            new_name='notificatio_user_id_1b1678_idx',
            old_name='notificatio_user_id_2f85f2_idx',
        ),
        migrations.RenameIndex(
            model_name='pushdevicetoken',
            new_name='notificatio_token_915919_idx',
            old_name='notificatio_token_f7b1b9_idx',
        ),
        migrations.RenameIndex(
            model_name='reservationreminder',
            new_name='notificatio_send_at_bc54fe_idx',
            old_name='notificatio_send_at_85c3c1_idx',
        ),
        migrations.RenameIndex(
            model_name='reservationreminder',
            new_name='notificatio_reserva_92ce05_idx',
            old_name='notificatio_reserva_b4a5c0_idx',
        ),
    ]
