# Generated by Django 5.2.6 on 2025-09-26 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceinplace',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_offered', to='users.placeprofile'),
        ),
        migrations.AddField(
            model_name='servicestype',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.servicescategory'),
        ),
        migrations.AddField(
            model_name='serviceinplace',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places_offering', to='services.servicestype'),
        ),
    ]
