# Generated by Django 5.2.6 on 2025-09-26 01:15
#
# NOTE: Operations were removed: 0001_initial already creates ServiceInPlace (with place,
# service) and ServicesType (with category). Re-applying those AddField ops fails on a
# fresh DB with "column already exists".

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("services", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = []
