# Generated by Django 5.2.6 on 2025-09-26 01:15
#
# NOTE: Operations removed: reservations.0001_initial already defines Reservation with
# client, place, professional, service. Re-applying AddField caused duplicate columns.

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reservations", "0001_initial"),
        ("services", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = []
