# Generated by Django 5.2.6 on 2026-02-28 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_tracking_requests'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='groupsession',
            new_name='reservation_date_e17b6e_idx',
            old_name='reservation_date_0ef64a_idx',
        ),
        migrations.RenameIndex(
            model_name='groupsession',
            new_name='reservation_provide_d7269c_idx',
            old_name='reservation_provide_dcf00f_idx',
        ),
        migrations.RenameIndex(
            model_name='trackingrequest',
            new_name='reservation_status_cc265a_idx',
            old_name='reservation_status_2288dc_idx',
        ),
        migrations.RenameIndex(
            model_name='trackingrequest',
            new_name='reservation_recipie_3cdfe9_idx',
            old_name='reservation_recipie_4e0222_idx',
        ),
    ]
