# Generated by Django 5.2.6 on 2026-03-17 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_rename_reservation_date_0ef64a_idx_reservation_date_e17b6e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupsession',
            name='sub_category',
            field=models.CharField(blank=True, help_text='Subcategory of the provider linked to this session', max_length=100, null=True),
        ),
    ]
