# Generated by Django 5.2.6 on 2025-10-29 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
        ('services', '0004_add_unified_service_model'),
        ('users', '0006_add_diagram_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(help_text='Rating from 1-5 stars')),
                ('message', models.TextField(blank=True, help_text='Review message/comment', null=True)),
                ('images', models.JSONField(blank=True, default=list, help_text='List of image URLs/paths')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_user', models.ForeignKey(help_text='User who wrote the review', on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(blank=True, help_text='Specific service being reviewed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='services.service')),
                ('to_public_profile', models.ForeignKey(help_text='Public profile being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to='users.publicprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('from_user', 'to_public_profile')},
            },
        ),
    ]
