# Generated by Django 5.2.6 on 2026-01-31 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_review_images_and_rating_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionalreview',
            name='professional',
        ),
        migrations.RemoveField(
            model_name='professionalreview',
            name='service',
        ),
        migrations.RemoveField(
            model_name='professionalreview',
            name='user',
        ),
        migrations.DeleteModel(
            name='PlaceReview',
        ),
        migrations.DeleteModel(
            name='ProfessionalReview',
        ),
    ]
