# Generated by Django 5.2.6 on 2025-12-02 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_integration', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='calendarevent',
            new_name='calendar_in_google__dc5836_idx',
            old_name='calendar_in_google__e2d7e5_idx',
        ),
        migrations.RenameIndex(
            model_name='calendarevent',
            new_name='calendar_in_calenda_a8b3d9_idx',
            old_name='calendar_in_calenda_7c8a68_idx',
        ),
    ]
