# Generated by Django 5.2.6 on 2025-12-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_integration', '0002_rename_calendar_in_google__e2d7e5_idx_calendar_in_google__dc5836_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleOAuthPendingCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(db_index=True, help_text='OAuth state parameter used to link authorization code', max_length=255, unique=True)),
                ('code', models.TextField(help_text='Authorization code from Google OAuth')),
                ('redirect_uri', models.URLField(help_text='Redirect URI used in the OAuth flow')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this code was received')),
            ],
            options={
                'verbose_name': 'Pending OAuth Code',
                'verbose_name_plural': 'Pending OAuth Codes',
                'indexes': [models.Index(fields=['state'], name='calendar_in_state_2b2e2d_idx')],
            },
        ),
    ]
