# Generated by Django 5.2.6 on 2025-10-21 05:51

import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmedia',
            name='media_file',
            field=models.FileField(storage=posts.models.MediaStorage(), upload_to='posts/media/'),
        ),
    ]
