# Generated by Django 5.2.6 on 2025-11-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_add_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('carousel', 'Carousel'), ('before_after', 'Before/After'), ('tips', 'Tips'), ('mosaic', 'Mosaic'), ('poll', 'Poll'), ('review', 'Review'), ('pet_adoption', 'Pet Adoption')], max_length=20),
        ),
    ]
