# Generated by Django 5.2.6 on 2025-10-28 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_availabilityschedule_customservice_timeslot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeprofile',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the place', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
