# Generated by Django 5.2.6 on 2025-10-28 05:37

import users.profile_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_placeprofile_description_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='image',
            field=models.ImageField(storage=users.profile_models.ProfileImageStorage(), upload_to='profile_images/'),
        ),
    ]
