# Generated by Django 5.2.6 on 2025-10-28 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profileimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Biography/About section for the place', null=True),
        ),
    ]
