# Generated by Django 5.2.6 on 2025-10-29 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_bio_to_place_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users/images/'),
        ),
        migrations.CreateModel(
            name='PublicProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_type', models.CharField(choices=[('PROFESSIONAL', 'Professional'), ('PLACE', 'Place')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_categories', models.JSONField(blank=True, default=list, help_text='List of sub-categories')),
                ('images', models.JSONField(blank=True, default=list, help_text='List of image URLs/paths')),
                ('linked_pros_place', models.JSONField(blank=True, default=list, help_text='List of linked professional/place IDs')),
                ('has_calendar', models.BooleanField(default=False, help_text='Whether this profile has calendar functionality')),
                ('street', models.CharField(blank=True, max_length=200, null=True)),
                ('number_ext', models.CharField(blank=True, max_length=20, null=True)),
                ('number_int', models.CharField(blank=True, max_length=20, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
