# Generated by Django 5.2.6 on 2025-10-29 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0006_add_diagram_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profileimage',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='profileimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('content_type', 'object_id'), name='unique_primary_image_per_profile'),
        ),
    ]
