# Generated by Django 5.2.6 on 2025-10-29 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_fix_profile_image_constraint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicprofile',
            options={'ordering': ['-created_at']},
        ),
    ]
