# Generated by Django 5.2.6 on 2025-11-01 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_add_coords_to_publicprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeprofile',
            name='category',
            field=models.CharField(blank=True, help_text='Main category (belleza, bienestar, mascotas)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='placeprofile',
            name='sub_categories',
            field=models.JSONField(blank=True, default=list, help_text='List of sub-categories'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='category',
            field=models.CharField(blank=True, help_text='Main category (belleza, bienestar, mascotas)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='sub_categories',
            field=models.JSONField(blank=True, default=list, help_text='List of sub-categories'),
        ),
    ]
