# Generated by Django 5.2.6 on 2025-11-22 20:10

from django.db import migrations, models


def convert_category_to_list(apps, schema_editor):
    """Convert existing category strings to lists"""
    PlaceProfile = apps.get_model('users', 'PlaceProfile')
    ProfessionalProfile = apps.get_model('users', 'ProfessionalProfile')
    PublicProfile = apps.get_model('users', 'PublicProfile')
    
    # Convert PlaceProfile categories
    for profile in PlaceProfile.objects.all():
        if profile.category and isinstance(profile.category, str):
            profile.category = [profile.category] if profile.category else []
            profile.save(update_fields=['category'])
    
    # Convert ProfessionalProfile categories
    for profile in ProfessionalProfile.objects.all():
        if profile.category and isinstance(profile.category, str):
            profile.category = [profile.category] if profile.category else []
            profile.save(update_fields=['category'])
    
    # Convert PublicProfile categories
    for profile in PublicProfile.objects.all():
        if profile.category and isinstance(profile.category, str):
            profile.category = [profile.category] if profile.category else []
            profile.save(update_fields=['category'])


def convert_category_to_string(apps, schema_editor):
    """Convert category lists back to strings (reverse migration)"""
    PlaceProfile = apps.get_model('users', 'PlaceProfile')
    ProfessionalProfile = apps.get_model('users', 'ProfessionalProfile')
    PublicProfile = apps.get_model('users', 'PublicProfile')
    
    # Convert PlaceProfile categories
    for profile in PlaceProfile.objects.all():
        if profile.category and isinstance(profile.category, list):
            profile.category = profile.category[0] if profile.category else None
            profile.save(update_fields=['category'])
    
    # Convert ProfessionalProfile categories
    for profile in ProfessionalProfile.objects.all():
        if profile.category and isinstance(profile.category, list):
            profile.category = profile.category[0] if profile.category else None
            profile.save(update_fields=['category'])
    
    # Convert PublicProfile categories
    for profile in PublicProfile.objects.all():
        if profile.category and isinstance(profile.category, list):
            profile.category = profile.category[0] if profile.category else None
            profile.save(update_fields=['category'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_place_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeprofile',
            name='category',
            field=models.JSONField(blank=True, default=list, help_text='List of main categories'),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='category',
            field=models.JSONField(blank=True, default=list, help_text='List of main categories'),
        ),
        migrations.AlterField(
            model_name='publicprofile',
            name='category',
            field=models.JSONField(blank=True, default=list, help_text='List of main categories'),
        ),
        migrations.RunPython(convert_category_to_list, convert_category_to_string),
    ]
