# Generated by Django 5.2.6 on 2025-11-22 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_place_links'),
    ]

    operations = [
        # Use RunSQL to alter column type with USING clause for data conversion
        migrations.RunSQL(
            # Forward: Convert CharField to JSONField with USING clause
            sql=[
                """
                ALTER TABLE users_placeprofile 
                ALTER COLUMN category TYPE jsonb 
                USING CASE
                    WHEN category IS NULL OR category = '' THEN '[]'::jsonb
                    ELSE jsonb_build_array(category)
                END;
                """,
                """
                ALTER TABLE users_professionalprofile 
                ALTER COLUMN category TYPE jsonb 
                USING CASE
                    WHEN category IS NULL OR category = '' THEN '[]'::jsonb
                    ELSE jsonb_build_array(category)
                END;
                """,
                """
                ALTER TABLE users_publicprofile 
                ALTER COLUMN category TYPE jsonb 
                USING CASE
                    WHEN category IS NULL OR category = '' THEN '[]'::jsonb
                    ELSE jsonb_build_array(category)
                END;
                """,
            ],
            # Reverse: Convert JSONField back to CharField
            reverse_sql=[
                """
                ALTER TABLE users_placeprofile 
                ALTER COLUMN category TYPE varchar(100) 
                USING CASE
                    WHEN category IS NULL OR category = '[]'::jsonb THEN NULL
                    WHEN jsonb_typeof(category) = 'array' AND jsonb_array_length(category) > 0 
                        THEN (category->>0)
                    ELSE NULL
                END;
                """,
                """
                ALTER TABLE users_professionalprofile 
                ALTER COLUMN category TYPE varchar(100) 
                USING CASE
                    WHEN category IS NULL OR category = '[]'::jsonb THEN NULL
                    WHEN jsonb_typeof(category) = 'array' AND jsonb_array_length(category) > 0 
                        THEN (category->>0)
                    ELSE NULL
                END;
                """,
                """
                ALTER TABLE users_publicprofile 
                ALTER COLUMN category TYPE varchar(100) 
                USING CASE
                    WHEN category IS NULL OR category = '[]'::jsonb THEN NULL
                    WHEN jsonb_typeof(category) = 'array' AND jsonb_array_length(category) > 0 
                        THEN (category->>0)
                    ELSE NULL
                END;
                """,
            ],
        ),
        # Update the field definition in Django's model state
        migrations.AlterField(
            model_name='placeprofile',
            name='category',
            field=models.JSONField(blank=True, default=list, help_text='List of main categories'),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='category',
            field=models.JSONField(blank=True, default=list, help_text='List of main categories'),
        ),
        migrations.AlterField(
            model_name='publicprofile',
            name='category',
            field=models.JSONField(blank=True, default=list, help_text='List of main categories'),
        ),
    ]
