# Generated by Django 5.2.6 on 2026-01-27 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_add_location_to_clientprofile'),
        ('users', '0016_google_auth_pending_code'),
    ]

    operations = [
    ]
