# Generated by Django 5.2.6 on 2026-01-31 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_add_address_coords_to_user'),
    ]

    operations = [
        # Index renames removed - indexes may not exist or have different names
        # These are auto-generated by Django and don't need manual renaming
    ]
