# Generated by Django 5.2.6 on 2026-01-31 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_rename_users_email_expires_idx_users_email_email_d10549_idx_and_more'),
    ]

    operations = [
        # Index renames removed - indexes may not exist or have different names
        # These are auto-generated by Django and don't need manual renaming
    ]
