# Generated by Django 5.2.6 on 2026-01-31 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_rename_users_email_expires_idx_users_email_email_d10549_idx_and_more'),
    ]

    operations = [
        # This migration is intentionally empty.
        # Django keeps trying to rename indexes that don't exist or have different names.
        # If you see future migrations trying to rename indexes, just remove the RenameIndex operations.
    ]
