# Generated by Django 5.2.6 on 2026-01-31 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_rename_users_email_expires_idx_users_email_email_d10549_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='emailauthcode',
            name='users_email_expires_idx',
        ),
        migrations.RemoveIndex(
            model_name='emailauthcode',
            name='users_email_consumed_idx',
        ),
        migrations.RemoveIndex(
            model_name='googleauthpendingcode',
            name='users_googlea_state_6aa9e3_idx',
        ),
    ]
