# Generated by Django 5.2.6 on 2026-01-31 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_remove_emailauthcode_users_email_expires_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='longitude',
        ),
    ]
