# Generated by Django 5.2.6 on 2026-02-13 06:01

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_add_city_to_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customservice',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=users.models.UserImageStorage(), upload_to='users/images/'),
        ),
    ]
