// Mock data for UI development - Static data to visualize components

export const mockProfessionals = [
  {
    id: 1,
    name: "Ana",
    last_name: "López",
    specialty: "Estilista Profesional",
    rating: 4.9,
    reviewsCount: 127,
    photo: null,
    bio: "Especialista en colorimetría y técnicas de balayage con más de 10 años de experiencia. Apasionada por resaltar la belleza natural de cada cliente.",
    city: "Ciudad de México",
    services: [1, 2, 3],
    portfolio: [
      {id: 1, image: null, description: "Balayage rubio"},
      {id: 2, image: null, description: "Corte en capas"},
      {id: 3, image: null, description: "Color fantasía"},
      {id: 4, image: null, description: "Peinado de novia"},
      {id: 5, image: null, description: "Ombre oscuro"},
      {id: 6, image: null, description: "Corte bob"},
    ],
    availability: {
      monday: ["09:00", "10:00", "11:00", "14:00", "15:00", "16:00"],
      tuesday: ["09:00", "10:00", "11:00", "14:00", "15:00", "16:00"],
      wednesday: ["09:00", "10:00", "11:00", "14:00", "15:00"],
      thursday: ["09:00", "10:00", "11:00", "14:00", "15:00", "16:00"],
      friday: ["09:00", "10:00", "11:00", "14:00", "15:00", "16:00", "17:00"],
      saturday: ["10:00", "11:00", "12:00", "13:00"],
      sunday: [],
    },
  },
  {
    id: 2,
    name: "Carlos",
    last_name: "Mendoza",
    specialty: "Barbero Profesional",
    rating: 4.8,
    reviewsCount: 89,
    photo: null,
    bio: "Experto en cortes clásicos y modernos para caballero. Especializado en barbería tradicional y diseños creativos.",
    city: "Guadalajara",
    services: [4, 5],
    portfolio: [
      {id: 7, image: null, description: "Fade clásico"},
      {id: 8, image: null, description: "Diseño de barba"},
      {id: 9, image: null, description: "Pompadour"},
      {id: 10, image: null, description: "Undercut"},
    ],
    availability: {
      monday: ["10:00", "11:00", "12:00", "15:00", "16:00", "17:00"],
      tuesday: ["10:00", "11:00", "12:00", "15:00", "16:00", "17:00"],
      wednesday: ["10:00", "11:00", "12:00", "15:00", "16:00"],
      thursday: ["10:00", "11:00", "12:00", "15:00", "16:00", "17:00"],
      friday: ["10:00", "11:00", "12:00", "15:00", "16:00", "17:00"],
      saturday: ["09:00", "10:00", "11:00", "12:00", "13:00"],
      sunday: [],
    },
  },
  {
    id: 3,
    name: "María",
    last_name: "García",
    specialty: "Maquilladora Profesional",
    rating: 5.0,
    reviewsCount: 156,
    photo: null,
    bio: "Maquillista certificada en técnicas de alta definición y maquillaje para eventos especiales. Trabajo personalizado para cada tipo de piel.",
    city: "Monterrey",
    services: [6, 7],
    portfolio: [
      {id: 11, image: null, description: "Maquillaje de novia"},
      {id: 12, image: null, description: "Look natural"},
      {id: 13, image: null, description: "Smokey eyes"},
      {id: 14, image: null, description: "Maquillaje editorial"},
      {id: 15, image: null, description: "Cejas perfectas"},
    ],
    availability: {
      monday: ["11:00", "13:00", "15:00", "17:00"],
      tuesday: ["11:00", "13:00", "15:00", "17:00"],
      wednesday: ["11:00", "13:00", "15:00", "17:00"],
      thursday: ["11:00", "13:00", "15:00", "17:00"],
      friday: ["11:00", "13:00", "15:00", "17:00"],
      saturday: ["10:00", "12:00", "14:00"],
      sunday: ["12:00", "14:00"],
    },
  },
  {
    id: 4,
    name: "Laura",
    last_name: "Sánchez",
    specialty: "Nail Artist",
    rating: 4.7,
    reviewsCount: 92,
    photo: null,
    bio: "Especialista en nail art y diseños personalizados. Técnicas de gelish, acrílico y decoración artística.",
    city: "Puebla",
    services: [8, 9],
    portfolio: [
      {id: 16, image: null, description: "Diseño floral"},
      {id: 17, image: null, description: "French manicure"},
      {id: 18, image: null, description: "Nail art geométrico"},
      {id: 19, image: null, description: "Uñas con glitter"},
    ],
    availability: {
      monday: ["09:00", "10:30", "12:00", "14:00", "15:30", "17:00"],
      tuesday: ["09:00", "10:30", "12:00", "14:00", "15:30", "17:00"],
      wednesday: ["09:00", "10:30", "12:00", "14:00", "15:30"],
      thursday: ["09:00", "10:30", "12:00", "14:00", "15:30", "17:00"],
      friday: ["09:00", "10:30", "12:00", "14:00", "15:30", "17:00"],
      saturday: ["10:00", "11:30", "13:00", "14:30"],
      sunday: [],
    },
  },
];

export const mockPlaces = [
  {
    id: 101,
    name: "Be-U Spa Premium",
    address: "Av. Reforma 123, Col. Centro",
    city: "Ciudad de México",
    country: "México",
    rating: 4.8,
    reviewsCount: 234,
    photo: null,
    description:
      "Spa de lujo con tratamientos faciales, corporales y servicios de belleza integral. Ambiente relajante y profesional.",
    services: [10, 11, 12],
    team: [
      {id: 1, name: "Ana López", specialty: "Estilista", rating: 4.9},
      {id: 2, name: "Sofia Ruiz", specialty: "Masajista", rating: 4.8},
      {id: 3, name: "Elena Castro", specialty: "Esteticista", rating: 5.0},
    ],
    gallery: [
      {id: 1, image: null, description: "Recepción"},
      {id: 2, image: null, description: "Sala de espera"},
      {id: 3, image: null, description: "Cabina de masajes"},
      {id: 4, image: null, description: "Área de manicure"},
      {id: 5, image: null, description: "Sala de tratamientos"},
      {id: 6, image: null, description: "Área de relajación"},
      {id: 7, image: null, description: "Vestidores"},
      {id: 8, image: null, description: "Zona de productos"},
    ],
    amenities: ["Estacionamiento", "WiFi", "Café", "Productos premium", "Música relajante"],
    hours: {
      monday: "9:00 AM - 8:00 PM",
      tuesday: "9:00 AM - 8:00 PM",
      wednesday: "9:00 AM - 8:00 PM",
      thursday: "9:00 AM - 8:00 PM",
      friday: "9:00 AM - 9:00 PM",
      saturday: "10:00 AM - 7:00 PM",
      sunday: "10:00 AM - 5:00 PM",
    },
  },
  {
    id: 102,
    name: "Salón Elegance",
    address: "Calle Juárez 456, Col. Americana",
    city: "Guadalajara",
    country: "México",
    rating: 4.6,
    reviewsCount: 156,
    photo: null,
    description:
      "Salón de belleza especializado en cortes, color y peinados para toda ocasión. Atención personalizada.",
    services: [1, 2, 3, 6],
    team: [
      {id: 4, name: "Carlos Mendoza", specialty: "Barbero", rating: 4.8},
      {id: 5, name: "Patricia Gómez", specialty: "Colorista", rating: 4.7},
    ],
    gallery: [
      {id: 9, image: null, description: "Entrada principal"},
      {id: 10, image: null, description: "Estaciones de corte"},
      {id: 11, image: null, description: "Área de lavado"},
      {id: 12, image: null, description: "Zona de color"},
    ],
    amenities: ["WiFi", "Café", "Revistas", "Música"],
    hours: {
      monday: "10:00 AM - 7:00 PM",
      tuesday: "10:00 AM - 7:00 PM",
      wednesday: "10:00 AM - 7:00 PM",
      thursday: "10:00 AM - 7:00 PM",
      friday: "10:00 AM - 8:00 PM",
      saturday: "9:00 AM - 6:00 PM",
      sunday: "Cerrado",
    },
  },
  {
    id: 103,
    name: "Studio Nails & Beauty",
    address: "Plaza del Sol Local 34",
    city: "Monterrey",
    country: "México",
    rating: 4.9,
    reviewsCount: 187,
    photo: null,
    description:
      "Estudio boutique especializado en nail art, manicure, pedicure y servicios de belleza de manos y pies.",
    services: [8, 9],
    team: [
      {id: 6, name: "Laura Sánchez", specialty: "Nail Artist", rating: 4.7},
      {id: 7, name: "Daniela Torres", specialty: "Pedicurista", rating: 4.9},
    ],
    gallery: [
      {id: 13, image: null, description: "Estaciones de manicure"},
      {id: 14, image: null, description: "Sillas de pedicure"},
      {id: 15, image: null, description: "Área de espera"},
      {id: 16, image: null, description: "Exhibición de diseños"},
    ],
    amenities: ["WiFi", "Netflix", "Snacks", "Bebidas"],
    hours: {
      monday: "9:00 AM - 7:00 PM",
      tuesday: "9:00 AM - 7:00 PM",
      wednesday: "9:00 AM - 7:00 PM",
      thursday: "9:00 AM - 7:00 PM",
      friday: "9:00 AM - 8:00 PM",
      saturday: "10:00 AM - 6:00 PM",
      sunday: "11:00 AM - 4:00 PM",
    },
  },
];

export const mockServices = [
  {
    id: 1,
    name: "Corte y Peinado",
    duration: "45 min",
    price: 500,
    description: "Corte personalizado según tu estilo",
  },
  {
    id: 2,
    name: "Color Completo",
    duration: "2 hrs",
    price: 1200,
    description: "Coloración completa con técnica profesional",
  },
  {
    id: 3,
    name: "Balayage",
    duration: "3 hrs",
    price: 1800,
    description: "Técnica de iluminación natural",
  },
  {
    id: 4,
    name: "Corte Caballero",
    duration: "30 min",
    price: 300,
    description: "Corte clásico o moderno",
  },
  {
    id: 5,
    name: "Barbería Completa",
    duration: "45 min",
    price: 450,
    description: "Corte + diseño de barba",
  },
  {
    id: 6,
    name: "Maquillaje Social",
    duration: "1 hr",
    price: 800,
    description: "Maquillaje para eventos",
  },
  {
    id: 7,
    name: "Maquillaje de Novia",
    duration: "2 hrs",
    price: 1500,
    description: "Maquillaje completo + prueba",
  },
  {
    id: 8,
    name: "Manicure Gelish",
    duration: "1 hr",
    price: 350,
    description: "Manicure con gelish de larga duración",
  },
  {
    id: 9,
    name: "Nail Art",
    duration: "1.5 hrs",
    price: 550,
    description: "Diseño personalizado en uñas",
  },
  {
    id: 10,
    name: "Facial Premium",
    duration: "1.5 hrs",
    price: 900,
    description: "Tratamiento facial profundo",
  },
  {
    id: 11,
    name: "Masaje Relajante",
    duration: "1 hr",
    price: 700,
    description: "Masaje corporal completo",
  },
  {
    id: 12,
    name: "Depilación Láser",
    duration: "30 min",
    price: 600,
    description: "Sesión de láser diodo",
  },
];

export const mockReviews = [
  {
    id: 1,
    providerId: 1,
    providerType: "professional",
    author: "María González",
    rating: 5,
    date: "2024-01-15",
    comment:
      "Excelente servicio! Ana es muy profesional y el resultado superó mis expectativas. El color quedó perfecto.",
    photos: [],
  },
  {
    id: 2,
    providerId: 1,
    providerType: "professional",
    author: "Sofía Ramírez",
    rating: 5,
    date: "2024-01-10",
    comment: "Me encantó mi nuevo look! Muy recomendada, sabe exactamente lo que te queda bien.",
    photos: [],
  },
  {
    id: 3,
    providerId: 2,
    providerType: "professional",
    author: "Roberto Díaz",
    rating: 5,
    date: "2024-01-12",
    comment: "Mejor barbero de la ciudad. Siempre salgo muy contento con el resultado.",
    photos: [],
  },
  {
    id: 4,
    providerId: 3,
    providerType: "professional",
    author: "Andrea Flores",
    rating: 5,
    date: "2024-01-08",
    comment: "María es increíble! Mi maquillaje de boda quedó hermoso y duró todo el día.",
    photos: [],
  },
  {
    id: 5,
    providerId: 1,
    providerType: "place",
    author: "Lucía Torres",
    rating: 5,
    date: "2024-01-14",
    comment: "El spa es hermoso y muy relajante. Los tratamientos son de primera calidad.",
    photos: [],
  },
  {
    id: 6,
    providerId: 1,
    providerType: "place",
    author: "Carmen Vega",
    rating: 4,
    date: "2024-01-09",
    comment: "Muy buen servicio, aunque un poco caro. Vale la pena por la calidad.",
    photos: [],
  },
  {
    id: 7,
    providerId: 2,
    providerType: "place",
    author: "Isabel Moreno",
    rating: 5,
    date: "2024-01-11",
    comment: "Me encanta este salón! Siempre me tratan super bien y los resultados son excelentes.",
    photos: [],
  },
  {
    id: 8,
    providerId: 3,
    providerType: "place",
    author: "Daniela Cruz",
    rating: 5,
    date: "2024-01-13",
    comment: "Mis uñas quedaron hermosas! El diseño es exactamente lo que quería.",
    photos: [],
  },
  {
    id: 9,
    providerId: 4,
    providerType: "professional",
    author: "Valentina Ortiz",
    rating: 5,
    date: "2024-01-07",
    comment: "Laura es una artista! Mis uñas siempre quedan perfectas.",
    photos: [],
  },
  {
    id: 10,
    providerId: 2,
    providerType: "professional",
    author: "Miguel Ángel",
    rating: 4,
    date: "2024-01-06",
    comment: "Buen corte y atención. El ambiente es muy profesional.",
    photos: [],
  },
];

export const mockPosts = [
  {
    id: 1,
    type: "before_after",
    author: {
      id: 1,
      name: "Ana López",
      specialty: "Estilista Profesional",
      photo: null,
    },
    content: {
      beforePhoto: null,
      afterPhoto: null,
      description:
        "Transformación completa con balayage y corte en capas. ¡El cambio perfecto para renovar tu look!",
      treatment: "Balayage + Corte",
      duration: "3 horas",
      products: ["Olaplex", "Tratamiento matizador"],
    },
    likes: 234,
    comments: 45,
    timestamp: "2024-01-15T10:30:00Z",
  },
  {
    id: 2,
    type: "video",
    author: {
      id: 2,
      name: "Carlos Mendoza",
      specialty: "Barbero Profesional",
      photo: null,
    },
    content: {
      video: null,
      thumbnail: null,
      title: "Técnica de Fade Perfecto",
      description:
        "Te muestro paso a paso cómo lograr un fade limpio y profesional. ¿Qué les parece el resultado?",
      duration: "0:45",
    },
    likes: 567,
    comments: 89,
    timestamp: "2024-01-14T15:20:00Z",
  },
  {
    id: 3,
    type: "photo",
    author: {
      id: 5,
      name: "Valentina Pérez",
      specialty: "Cliente",
      photo: null,
    },
    content: {
      photos: [null, null, null],
      description:
        "¡Feliz con mi nuevo look! Gracias @AnaLopez por hacer realidad lo que quería ✨💇‍♀️",
      location: "Be-U Spa Premium",
    },
    likes: 128,
    comments: 23,
    timestamp: "2024-01-14T12:00:00Z",
  },
  {
    id: 4,
    type: "tips",
    author: {
      id: 100,
      name: "Be-U Admin",
      specialty: "Consejos de Belleza",
      photo: null,
    },
    content: {
      title: "5 Tips para Cuidar tu Cabello Teñido",
      image: null,
      tips: [
        "Usa shampoo sin sulfatos para mantener el color",
        "Aplica mascarilla nutritiva 2 veces por semana",
        "Evita el agua muy caliente al lavar",
        "Protege tu cabello del sol con productos UV",
        "Agenda retoques cada 6-8 semanas",
      ],
      category: "Cabello",
      difficulty: "Fácil",
      time: "5 min lectura",
    },
    likes: 892,
    comments: 156,
    timestamp: "2024-01-13T09:00:00Z",
  },
  {
    id: 5,
    type: "review",
    author: {
      id: 6,
      name: "Sofía Ramírez",
      specialty: "Cliente",
      photo: null,
    },
    content: {
      provider: {
        id: 3,
        name: "María García",
        type: "professional",
      },
      rating: 5,
      aspects: {
        quality: 5,
        cleanliness: 5,
        attention: 5,
        value: 5,
      },
      photos: [null],
      description:
        "Increíble experiencia! María es súper profesional y el maquillaje me duró perfecto todo el evento. 100% recomendada 💄✨",
      wouldRecommend: true,
    },
    likes: 67,
    comments: 12,
    timestamp: "2024-01-12T18:30:00Z",
  },
  {
    id: 6,
    type: "mosaic",
    author: {
      id: 4,
      name: "Laura Sánchez",
      specialty: "Nail Artist",
      photo: null,
    },
    content: {
      photos: [null, null, null, null, null, null],
      layout: "3x2",
      title: "Diseños de la Semana",
      description: "Mis diseños favoritos de esta semana. ¿Cuál te gusta más? 💅✨",
      tags: ["#nailart", "#gelish", "#diseñospersonalizados"],
    },
    likes: 445,
    comments: 78,
    timestamp: "2024-01-11T16:45:00Z",
  },
  {
    id: 7,
    type: "poll",
    author: {
      id: 100,
      name: "Be-U Admin",
      specialty: "Encuestas",
      photo: null,
    },
    content: {
      question: "¿Qué servicio te gustaría probar este mes?",
      options: [
        {id: 1, text: "Balayage", votes: 234},
        {id: 2, text: "Nail Art", votes: 189},
        {id: 3, text: "Tratamiento Facial", votes: 156},
        {id: 4, text: "Maquillaje Profesional", votes: 98},
      ],
      totalVotes: 677,
      duration: "3 días",
      image: null,
      allowMultiple: false,
      endsAt: "2024-01-18T23:59:59Z",
    },
    likes: 234,
    comments: 56,
    timestamp: "2024-01-10T10:00:00Z",
  },
];

// Available time slots for booking
export const mockAvailableSlots = [
  "09:00",
  "09:30",
  "10:00",
  "10:30",
  "11:00",
  "11:30",
  "12:00",
  "14:00",
  "14:30",
  "15:00",
  "15:30",
  "16:00",
  "16:30",
  "17:00",
  "17:30",
];

// Post format options
export const postFormats = [
  {
    id: "video",
    icon: "videocam",
    title: "Video + Descripción",
    description: "Comparte tu trabajo en video",
    roles: ["PROFESSIONAL", "PLACE"],
    color: "#FF6B6B",
  },
  {
    id: "photo",
    icon: "camera",
    title: "Foto + Descripción",
    description: "Comparte una foto",
    roles: ["CLIENT", "PROFESSIONAL", "PLACE"],
    color: "#4ECDC4",
  },
  {
    id: "before_after",
    icon: "swap-horizontal",
    title: "Antes/Después",
    description: "Muestra tu transformación",
    roles: ["PROFESSIONAL", "PLACE"],
    color: "#FFD93D",
  },
  {
    id: "tips",
    icon: "bulb",
    title: "Tips",
    description: "Comparte consejos",
    roles: ["ADMIN"],
    color: "#6BCF7F",
  },
  {
    id: "mosaic",
    icon: "grid",
    title: "Mosaico",
    description: "Galería de fotos",
    roles: ["PROFESSIONAL", "PLACE"],
    color: "#FF8A65",
  },
  {
    id: "poll",
    icon: "bar-chart",
    title: "Encuesta",
    description: "Crea una encuesta",
    roles: ["ADMIN"],
    color: "#64B5F6",
  },
];
